# Generated by Django 5.1.2 on 2024-10-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_restaurant_random_products'),
        ('resto_preview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
    ]
