# Generated by Django 5.1.4 on 2024-12-21 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resto_preview", "0003_selfrating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SelfRating",
        ),
    ]
