# Generated by Django 5.1.2 on 2024-10-25 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_restaurant_random_products'),
        ('resto_preview', '0003_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
    ]
