# Generated by Django 5.1.2 on 2024-10-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto_preview', '0007_remove_rating_food_remove_rating_score_rating_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='scores',
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
