# Generated by Django 5.1.2 on 2024-10-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resto_preview", "0008_remove_rating_scores_rating_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.IntegerField(),
        ),
    ]
