# Generated by Django 5.1.2 on 2024-10-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto_preview', '0009_alter_rating_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_resto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('random_products', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
