# Generated by Django 5.1.2 on 2024-10-27 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "resto_preview",
            "0011_alter_rating_unique_together_follow_created_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="show_resto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=255)),
                ("kategori", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
                ("random_products", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="follow",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resto_preview.show_resto",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resto_preview.show_resto",
            ),
        ),
        migrations.RemoveField(
            model_name="follow",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="created_at",
        ),
    ]
