# Generated by Django 5.1.2 on 2024-10-26 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_restaurant_random_products_food_image_url_and_more'),
        ('resto_preview', '0011_alter_follow_restaurant_alter_rating_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
    ]
