# Generated by Django 5.1.2 on 2024-10-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto_preview', '0012_alter_follow_restaurant_alter_rating_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='show_resto',
        ),
    ]
