# Generated by Django 5.1.2 on 2024-10-26 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto_preview', '0013_delete_show_resto'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_resto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('random_products', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='follow',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto_preview.show_resto'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto_preview.show_resto'),
        ),
    ]
