# Generated by Django 5.1.2 on 2024-10-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='reported_by',
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.post'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('Konten Tidak Pantas', 'Konten Tidak Pantas'), ('Spam atau Iklan', 'Spam atau Iklan'), ('Bahasa Kasar atau Menyinggung', 'Bahasa Kasar atau Menyinggung'), ('Misinformasi', 'Misinformasi'), ('Topik Tidak Relevan', 'Topik Tidak Relevan')], max_length=50),
        ),
    ]
