# Generated by Django 5.1.2 on 2024-10-26 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_rename_user_report_reported_by_alter_report_post_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Share",
        ),
    ]
