# Generated by Django 5.1.2 on 2024-10-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_restaurant_random_products_alter_food_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='random_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
