# Generated by Django 5.1.2 on 2024-11-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
