# Generated by Django 5.1.2 on 2024-10-26 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_food_image_url_alter_food_diskon"),
        ("main", "0003_alter_restaurant_random_products"),
    ]

    operations = []
