# Generated by Django 5.1.2 on 2024-10-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_restaurant_random_products_food_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image_url',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='random_products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='food',
            name='diskon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
