# Generated by Django 5.1.2 on 2024-10-26 22:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_restaurant_random_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="harga",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
