# Generated by Django 5.1.2 on 2024-10-27 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_food_harga_alter_restaurant_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed_restaurants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="random_products",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
