# Generated by Django 5.1.2 on 2024-10-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_remove_restaurant_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="random_products",
        ),
        migrations.AddField(
            model_name="food",
            name="image",
            field=models.ImageField(default="../static/image/noimg.jpg", upload_to=""),
        ),
    ]
